### ISSUE TITLE
Blocks discovery of new plugin versions (especially WP rockeT)

### ISSUE THREAD

**Issue by GeorgBNM** [WordPress/classic-widgets#10]
Hi,

as I updated this plugin to the latest version, the updates for other plugins are disappearing.
In my case this is WP Rocket, maybe some others are involved also?

WP core: 5.8.1

Can you please fix this?

Best,
GeorgBNM

**Comment by ironprogrammer** [comment]
Hi, @GeorgBNM! This plugin shouldn't have impacted the way WordPress checks for other plugin updates.

Was this issue resolved, or is it still a problem?

**Comment by GeorgBNM** [comment]
Hi @ironprogrammer,

Thanks for coming back to me.
As there are some months disappearing, we got rid of WP Rocket in the meantime and the problem is gone.

Wish you all the best!

Cheers,
Georg
