### ISSUE TITLE
need to backrev to version 0.2 how can i get it?

### ISSUE THREAD

**Issue by redhorse61270** [WordPress/classic-widgets#22]
host autoupdated plugin, and now i haveno access to what it is calling legacy widget.

**Comment by ironprogrammer** [comment]
Hi, @redhorse61270 👋🏻 

On the plugin's [Advanced View](https://wordpress.org/plugins/classic-widgets/advanced/) tab, scroll down to "Advanced Options" and you can find specific older versions to download.
