### ISSUE TITLE
New Comments do now show up 

### ISSUE THREAD

**Issue by jlapac** [WordPress/classic-widgets#23]
I added the Classic Widgets plugin and it is now up to date. New comments are still not showing up in the sidebar. Are there settings that need to be adjusted? The FAQ says no. 
I use the Twenty-Sixteen theme. Is that the problem? 
[comment-classic-widget.pdf](https://github.com/user-attachments/files/16881161/comment-classic-widget.pdf)

Thanks!
Jaye

**Comment by StevenDufresne** [comment]
You should probably open an issue in the forums for support: 
https://wordpress.org/support/plugin/classic-widgets/

**Comment by jlapac** [comment]
I am not able to create a new topic in that forum even though I logged in. I went to the GitHub forum as that was the link provided in the footer of the plugin. 

 

Let me know if you have other ideas.

Thank you!

Jaye
